id: I314863A7
legacy_id: P004271
ocr_import_info:
  bdrc_scan_id: W1GS66248
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T15:24:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T21:04:56.573789+00:00'
last_modified: 2022-08-31 05:05:09.000618
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1GS66248
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1GS66248
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གབ་ཙེ་སུམ་ཅུ་སོ་བཞིའི་མོ་དཔེ།
statistics:
  ocr_word_mean_confidence_index: 0.5376548849999006
  ocr_word_median_confidence_index: 0.5199999809265137
quality: null
bases:
  I1GS66250:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS66250
      total_pages: 76
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS66250.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5376548849999006
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
