id: P004271
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1GS66248
  title: གབ་ཙེ་སུམ་ཅུ་སོ་བཞིའི་མོ་དཔེ
  author: ''
  volumes:
    8204a5ce9cc04614a10b570253ad303d:
      image_group_id: I1GS66250
      title: ''
      volume_number: 1
      total_pages: 76
      base_file: v001.txt
